name: GazeTracking
channels:
  - conda-forge
  - anaconda
  - defaults
dependencies:
  - python=3.10  # Specify Python version explicitly
  - numpy==1.16.1
  - opencv=3.4.*
  - dlib=19.17.*
  - flask==3.1.0
  - blinker==1.9.0
  - click==8.1.8
  - colorama==0.4.6
  - itsdangerous==2.2.0
  - Jinja2==3.1.5
  - MarkupSafe==3.0.2
  - Werkzeug==3.1.3
  - pip
  - pip:
      - gaze-tracking==0.0.1
